### PR TITLE
rely/deny

### PR DESCRIPTION
**Pull request by nanexcool**

### CODE REVIEW

**Comment by nmushegian** [comment]
?? @dbrock simplification ?

**Comment by nanexcool** [comment]
@nmushegian he suggested `uint(-1)` instead of `2 ** 256 - 1`

**Comment by nmushegian** [comment]
ah I was looking at the diff before the use of a CONSTANT was restored

**Comment by nmushegian** [comment]
I'm not sure about the use of a magic constant for this... seems like the caller could also have that as some magic value also, or try to maintain a double entry, or something like that.

making it explicit would require an extra storage per entry and lookup per lookup

**Comment by nmushegian** [comment]
what do you think of this https://github.com/dapphub/ds-token/pull/15

**Comment by nanexcool** [comment]
@nmushegian looks good! I like how you handle allowance... how will you set it? something like:
```
function meme(address dst, bool yay) {
    deps[msg.sender][dst] = yay;
}
```
Also what about name, symbol and decimals?

**Comment by nmushegian** [comment]
@nanexcool 
> Also what about name, symbol and decimals? Or are you burning the whole house down??

no survivors =]]]

**Comment by nmushegian** [comment]
closing this in favor of https://github.com/dapphub/ds-token/pull/15

**Pull request closed without merging**
