### PR TITLE
Adds stop and start to ds-token

### PR DESCRIPTION
**Pull request by nanexcool**
Tests are incoming while we figure out what's wrong with `dapp test`.

### CODE REVIEW

**Comment by nmushegian** [comment]
`start` -> `flow` ? =]  @dbrock

**Comment by nanexcool** [comment]
`release_the_kraken`?

**Comment by nmushegian** [comment]
I like flow because it rhymes with 'go'

**Comment by nanexcool** [comment]
Fixed a couple of existing issues.

Tests were using a constructor for setup instead of `setUp()`, that's why they were behaving incorrectly.

Added some new tests to `DSToken`.

**Comment by dbrock** [comment]
Good job @nanexcool 

Re names, I like `stop` and `stir`

@nmushegian u liek?

**Pull request closed without merging**
